name: Volunteers
on:
  schedule:
    - cron: '45 * * * *'

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          ref: master
          repository: 'COVID19Tracking/covid-public-api'
          token: ${{ secrets.API_DEPLOY_TOKEN }}
          path: ./_api

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Build API files
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
        run: |
          npm run build:volunteers
          npm run test:post-build

      - name: Commit API files
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update volunteer data
          repository: ./_api
          file_pattern: ./**
          commit_author: COVID Tracking Project API Builder <accounts@covidtracking.com>
